#ifndef __GE_FDC_H__
#define __GE_FDC_H__
#include <asm/arch/base.h>
#define CONFIG_SYS_LOAD_ADDR		0x40100000UL /* load address */

/*
 * Size of malloc() pool
 */
#define CONFIG_SYS_MALLOC_LEN	(4 * 1024 * 1024)

#define CONFIG_SYS_INIT_RAM_ADDR    0xE63A0000UL 
#define CONFIG_SYS_INIT_RAM_SIZE    0x12000UL 
#define CONFIG_SYS_INIT_SP_OFFSET   (CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE) 
#define CONFIG_SYS_INIT_SP_ADDR     (CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)
#define CONFIG_SPL_STACK            (CONFIG_SYS_INIT_SP_ADDR)


#define CONFIG_SYS_SDRAM_BASE       0x40000000UL
#define CONFIG_SYS_DEBUG_UART_BASE  0xE6E58000UL
#define CONFIG_SYS_UBOOT_BASE       0x10000000UL
#endif
