#
# arch/arm/cpu/armv7/d1h/Makefile
# 	This file defines board-related files for make.
#
# Copyright (C) 2015-2016 Songxue.Xu
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += clock.o
obj-y += cpu.o
obj-y += sdram.o
obj-y += sfma.o
obj-y += timer.o